[build]
  publish = "frontend/build"
  command = "npm install && cd frontend && npm install && npm run build:ci"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd frontend && npm start"
  port = 3000
  publish = "frontend/build"
  functions = "netlify/functions"
